version: '3'

services:
        spring-boot:
                build:
                        context: ./
                        dockerfile: Dockerfile
                ports:
                - "8888:8081"
